apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: akpfs-frontend
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
  - name: deploy-trigger-for-frontend
    interceptors:
    - github:
        eventTypes: ["push"]
    - cel:
        filter: "body.repository.name == 'team-gemini' && body.ref.split('/')[2] == 'frontend'"
    bindings:
      - ref: team-gemini-pipeline-triggerbinding-frontend
    template:
      ref: team-gemini-triggertemplate-frontend
