apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: team-gemini-pipeline-triggerbinding-frontend
spec:
  params:
    - name: namespace
      value: team-gemini
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: gitrepositoryname
      value: $(body.repository.name)
