apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: akpfs
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
        - ref: team-gemini-pipeline-triggerbinding
      template:
        ref: team-gemini-triggertemplate
