apiVersion: v1
kind: Service
metadata:
  labels:
    app: team-gemini-frontend
    app.kubernetes.io/instance: team-gemini
    app.kubernetes.io/name: team-gemini
  name: team-gemini-frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: team-gemini
    app.kubernetes.io/name: team-gemini
  sessionAffinity: None
  type: ClusterIP